'use client';
import { useEffect, useState, useRef } from 'react';
import { useRouter } from 'next/navigation';
import type { SessionSnapshot } from '@/types/core';
import InviteFriends from '@/components/InviteFriends';
import { Avatar, AvatarGroup } from '@/components/ui/avatar';
import { Celebration } from '@/components/Celebration';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { addToSessionHistory, updateSessionHistory } from '@/lib/session-history';
import { CheckCircle, Users, Clock, Copy, ArrowRight, Sparkles } from 'lucide-react';

export default function SyncPage({ params }: { params: Promise<{ sessionId: string }> }) {
  const router = useRouter();
  const [sessionId, setSessionId] = useState<string | null>(null);
  const [snap, setSnap] = useState<SessionSnapshot | null>(null);
  const [err, setErr] = useState<string | null>(null);
  const [inviteOpen, setInviteOpen] = useState(false);
  const [hasOpenedInvite, setHasOpenedInvite] = useState(false);
  const [hasCelebrated, setHasCelebrated] = useState(false);
  const previousFinalMatch = useRef<string | null>(null);

  // Handle async params
  useEffect(() => {
    params.then((resolvedParams) => {
      if (resolvedParams?.sessionId) {
        setSessionId(resolvedParams.sessionId);
      }
    });
  }, [params]);

  useEffect(() => {
    if (!sessionId) return;
    
    let alive = true;
    async function tick() {
      try {
        const res = await fetch(`/api/session/${sessionId}/status`, { cache: 'no-store' });
        if (!res.ok) throw new Error('status_failed');
        const data = (await res.json()) as SessionSnapshot;
        if (alive) {
          setSnap(data);
          setErr(null);

          // Trigger celebration when final match appears for the first time
          if (data.finalMatch && !previousFinalMatch.current) {
            setHasCelebrated(true);
            previousFinalMatch.current = data.finalMatch.key;

            // Add to session history
            if (sessionId) {
              addToSessionHistory({
                sessionId,
                name: 'Group Session',
                matchKey: data.finalMatch.key,
                confidence: data.finalMatch.confidence,
                participantCount: data.counts.total,
                expiresAt: Date.now() + 48 * 60 * 60 * 1000, // 48 hours
              });
            }
          } else if (data.finalMatch && previousFinalMatch.current && sessionId) {
            // Update session history if match changes
            updateSessionHistory(sessionId, {
              matchKey: data.finalMatch.key,
              confidence: data.finalMatch.confidence,
            });
          }
        }
      } catch (e: any) {
        if (alive) setErr(e?.message || 'failed');
      }
    }
    tick();
    const id = setInterval(tick, 3000);
    return () => { alive = false; clearInterval(id); };
  }, [sessionId]);

  const getVibeEmoji = (key?: string) => {
    const emojiMap: Record<string, string> = {
      'cozy-creative': '🎨',
      'chill-social': '☕',
      'lowkey-game': '🎮',
      'mini-adventure': '🗺️',
      'talk-taste': '🍷',
      'music-mingle': '🎵',
    };
    return emojiMap[key || ''] || '✨';
  };

  const handleCopyPlan = () => {
    if (!snap?.finalMatch || !snap?.suggestions) return;

    const text = `🎯 Group Plan: ${snap.finalMatch.key}

👥 Participants: ${snap.participants.map(p => p.name).join(', ')}
📊 Confidence: ${Math.round(snap.finalMatch.confidence * 100)}%

📋 Suggestions:
${snap.suggestions.map((s, i) => `${i + 1}. ${s.title}${s.desc ? ` - ${s.desc}` : ''}`).join('\n')}

🔗 View full details: ${window.location.origin}/sync/${sessionId}

Generated by Vibe Deck`;

    navigator.clipboard?.writeText(text).then(() => {
      alert('Plan copied to clipboard!');
    }).catch(() => {
      alert('Failed to copy plan');
    });
  };

  if (err) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-red-400 via-pink-500 to-orange-400 relative overflow-hidden flex items-center justify-center">
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute -top-40 -right-40 w-80 h-80 bg-red-300 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-blob"></div>
          <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-pink-300 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-blob animation-delay-2000"></div>
        </div>
        <div className="text-center max-w-md mx-auto px-4 relative z-10 bg-white/80 backdrop-blur-xl border border-white/30 shadow-2xl shadow-red-500/20 rounded-2xl p-8">
          <div className="text-red-600 mb-4 font-semibold">Error: {String(err)}</div>
          <Button onClick={() => window.location.reload()} className="bg-gradient-to-r from-red-500 to-pink-500 hover:from-red-600 hover:to-pink-600 text-white shadow-lg shadow-red-500/30">Try Again</Button>
        </div>
      </div>
    );
  }

  if (!snap) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-purple-400 via-pink-500 to-orange-400 relative overflow-hidden flex items-center justify-center">
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute -top-40 -right-40 w-80 h-80 bg-purple-300 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-blob"></div>
          <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-pink-300 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-blob animation-delay-2000"></div>
        </div>
        <div className="text-center relative z-10 bg-white/80 backdrop-blur-xl border border-white/30 shadow-2xl shadow-purple-500/20 rounded-2xl p-8">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-purple-600 mx-auto mb-4"></div>
          <p className="text-gray-700 font-medium">Loading session…</p>
        </div>
      </div>
    );
  }

  const { participants, counts, provisionalMatch, finalMatch, suggestions } = snap;
  const progressPercentage = counts.total > 0 ? (counts.completed / counts.total) * 100 : 0;

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-400 via-pink-500 to-orange-400 relative overflow-hidden">
      {/* Animated background elements */}
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute -top-40 -right-40 w-80 h-80 bg-purple-300 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-blob"></div>
        <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-pink-300 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-blob animation-delay-2000"></div>
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-80 h-80 bg-orange-300 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-blob animation-delay-4000"></div>
      </div>
      {/* Celebration animation */}
      {finalMatch && hasCelebrated && <Celebration trigger={hasCelebrated} intensity="high" />}

      <div className="container mx-auto px-4 py-8 max-w-4xl relative z-10">
        {/* Header */}
        <div className="flex items-center justify-between mb-6 bg-white/70 backdrop-blur-xl border border-white/30 shadow-2xl shadow-purple-500/10 rounded-2xl p-6">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 mb-1">Friend Sync</h1>
            <p className="text-sm text-gray-600 font-medium">
              {counts.completed === counts.total && finalMatch
                ? 'Match found! 🎉'
                : 'Waiting for friends to complete swiping...'}
            </p>
          </div>
          <Button
            onClick={async () => {
              setInviteOpen(true);
              setHasOpenedInvite(true);
              if (sessionId) {
                const mod = await import('@/lib/analytics').catch(() => ({ capture: async () => {} }));
                (mod as any).capture?.('invite_opened', { sessionId });
              }
            }}
            className="bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white shadow-lg shadow-purple-500/30"
          >
            <Users className="h-4 w-4 mr-2" />
            Invite friends
          </Button>
        </div>

        {hasOpenedInvite && (
          <div className="rounded-xl bg-blue-500/80 backdrop-blur-md border border-blue-400/30 p-4 text-sm text-white font-medium mb-6 shadow-lg shadow-blue-500/20">
            💡 Share the <strong>join</strong> link (it looks like /s/•••). Friends will swipe first, then appear here.
          </div>
        )}

        {/* Progress Card */}
        <Card className="mb-6 bg-white/70 backdrop-blur-xl border border-white/30 shadow-2xl shadow-purple-500/10 rounded-2xl">
          <CardHeader>
            <CardTitle className="flex items-center justify-between">
              <span className="flex items-center gap-2">
                <Users className="h-5 w-5" />
                Progress
              </span>
              <Badge variant="secondary">
                {counts.completed}/{counts.total} completed
              </Badge>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <Progress value={progressPercentage} className="mb-4" />
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {participants.map((p) => (
                <div
                  key={p.id}
                  className="flex items-center justify-between p-4 bg-white/60 backdrop-blur-md rounded-xl border border-white/20 hover:bg-white/80 transition-all hover:shadow-lg shadow-purple-500/10"
                >
                  <div className="flex items-center gap-3">
                    <Avatar name={p.name} size="sm" />
                    <span className="font-medium">{p.name}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    {p.state === 'completed' ? (
                      <Badge variant="default" className="bg-green-600">
                        <CheckCircle className="h-3 w-3 mr-1" />
                        Done
                      </Badge>
                    ) : p.state === 'swiping' ? (
                      <Badge variant="secondary">
                        <Clock className="h-3 w-3 mr-1" />
                        Swiping
                      </Badge>
                    ) : (
                      <Badge variant="outline">Waiting</Badge>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Final Match */}
        {finalMatch ? (
          <Card className="mb-6 bg-white/80 backdrop-blur-xl border border-green-400/30 shadow-2xl shadow-green-500/20 rounded-2xl">
            <CardHeader>
              <CardTitle className="flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <span className="text-3xl">{getVibeEmoji(finalMatch.key)}</span>
                  <span className="capitalize">{finalMatch.key.replace('-', ' ')}</span>
                </span>
                <Badge variant="secondary" className="bg-green-100 text-green-800">
                  {Math.round(finalMatch.confidence * 100)}% match
                </Badge>
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-3 mb-4">
                {(suggestions ?? []).slice(0, 5).map((s, i) => (
                  <div
                    key={i}
                    className="p-4 bg-white/70 backdrop-blur-md rounded-xl border border-green-300/30 hover:bg-white/90 transition-all shadow-lg shadow-green-500/10"
                  >
                    <div className="font-semibold text-gray-900 mb-1">{s.title}</div>
                    {s.desc && (
                      <div className="text-sm text-gray-600">{s.desc}</div>
                    )}
                  </div>
                ))}
              </div>
              <div className="flex gap-3">
                <Button onClick={handleCopyPlan} className="flex-1 bg-gradient-to-r from-green-500 to-emerald-500 hover:from-green-600 hover:to-emerald-600 text-white shadow-lg shadow-green-500/30">
                  <Copy className="h-4 w-4 mr-2" />
                  Copy Plan
                </Button>
                <Button
                  onClick={() => sessionId && router.push(`/plan/${sessionId}`)}
                  className="flex-1 bg-white/80 backdrop-blur-xl border border-white/30 hover:bg-white/90 shadow-lg shadow-purple-500/20 text-gray-900 font-semibold"
                  disabled={!sessionId}
                >
                  <ArrowRight className="h-4 w-4 mr-2" />
                  View Details
                </Button>
              </div>
            </CardContent>
          </Card>
        ) : provisionalMatch ? (
          <Card className="mb-6 bg-white/80 backdrop-blur-xl border border-yellow-400/30 shadow-2xl shadow-yellow-500/20 rounded-2xl">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Sparkles className="h-5 w-5" />
                Provisional Match
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center justify-between">
                <div>
                  <div className="text-lg font-semibold mb-1">
                    <span className="text-2xl mr-2">{getVibeEmoji(provisionalMatch.key)}</span>
                    <span className="capitalize">{provisionalMatch.key.replace('-', ' ')}</span>
                  </div>
                  <div className="text-sm text-gray-600">
                    {Math.round(provisionalMatch.confidence * 100)}% confidence
                  </div>
                </div>
                <Badge variant="secondary" className="bg-yellow-100 text-yellow-800">
                  Waiting for more friends…
                </Badge>
              </div>
            </CardContent>
          </Card>
        ) : (
          <Card className="mb-6 bg-white/70 backdrop-blur-xl border border-white/30 shadow-2xl shadow-purple-500/10 rounded-2xl">
            <CardContent className="p-6 text-center text-gray-700">
              <Clock className="h-8 w-8 mx-auto mb-2 text-purple-400" />
              <p className="font-medium">Waiting for matches…</p>
              <p className="text-sm mt-2 text-gray-600">
                Need at least 2 participants to see a match
              </p>
            </CardContent>
          </Card>
        )}

        {sessionId && (
          <InviteFriends sessionId={sessionId} open={inviteOpen} onClose={() => setInviteOpen(false)} />
        )}
      </div>
    </div>
  );
}
